inputs_def:
  - handle: input_dir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: output_dir
    json_schema:
      type: string
      ui:widget: dir
  - handle: lang
    json_schema:
      enum:
        - CHS
        - CHT
        - ENG
        - JPN
        - KOR
        - FRA
        - DEU
        - RUS
      ui:options:
        labels:
          - Simplified Chinese
          - Traditional Chinese
          - English
          - Japanese
          - Korean
          - French
          - German
          - Russian
outputs_def:
  - handle: output_files
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Manga
icon: ":twemoji:japanese-secret-button:"
