inputs_def:
  - handle: input_files
    description: Input
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
  - handle: output_folder
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
  - handle: target_language
    json_schema:
      enum:
        - CHS
        - CHT
        - CSY
        - NLD
        - ENG
        - FRA
        - DEU
        - HUN
        - ITA
        - JPN
        - KOR
        - PLK
        - PTB
        - ROM
        - RUS
        - ESP
        - TRK
        - UKR
        - VIN
        - CNR
        - SRP
        - HRV
        - ARA
        - THA
        - IND
      ui:options:
        labels:
          - 简体中文
          - 繁體中文
          - Čeština
          - Nederlands
          - English
          - Français
          - Deutsch
          - Magyar
          - Italiano
          - 日本語
          - 한국어
          - Polski
          - Português
          - Română
          - Русский
          - Español
          - Türkçe
          - Українська
          - Tiếng Việt
          - Crnogorski
          - Српски
          - Hrvatski
          - العربية
          - ไทย
          - Bahasa Indonesia
    nullable: false
  - group: more
    collapsed: true
  - handle: source_language
    json_schema:
      enum:
        - auto
        - CHS
        - CHT
        - CSY
        - NLD
        - ENG
        - FRA
        - DEU
        - HUN
        - ITA
        - JPN
        - KOR
        - PLK
        - PTB
        - ROM
        - RUS
        - ESP
        - TRK
        - UKR
        - VIN
        - CNR
        - SRP
        - HRV
        - ARA
        - THA
        - IND
      ui:options:
        labels:
          - auto
          - 简体中文
          - 繁體中文
          - Čeština
          - Nederlands
          - English
          - Français
          - Deutsch
          - Magyar
          - Italiano
          - 日本語
          - 한국어
          - Polski
          - Português
          - Română
          - Русский
          - Español
          - Türkçe
          - Українська
          - Tiếng Việt
          - Crnogorski
          - Српски
          - Hrvatski
          - العربية
          - ไทย
          - Bahasa Indonesia
    value: auto
  - handle: device
    json_schema:
      enum:
        - cuda
        - cpu
      ui:options:
        labels:
          - CUDA
          - CPU
    value: cuda
  - handle: llm
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: deepseek-chat
      temperature: 1
      top_p: 0.8
      max_tokens: 4096
outputs_def:
  - handle: output_files
    json_schema:
      type: array
      items:
        type: string
        ui:widget: save
  - handle: output_folder
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 494.8602769400437
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Translate manga images
